# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.1.0"

gem "jsbundling-rails", "~> 1.3"
gem "puma", ">= 5.0"
gem "rails", "~> 7.1.3"
gem "sprockets"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "daisyui-view-components", path: '../daisyui-view-components'

gem "bootsnap", require: false
gem "tzinfo-data", platforms: [:mswin, :mswin64, :mingw, :x64_mingw, :jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "pry-remote"
end

group :development do
  gem "lookbook", ">= 2.2.1"
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "web-console"
end
